ecommerce_lakehouse:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: ecommerce
      schema: gold
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: /sql/1.0/warehouses/your_warehouse_id
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
